# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install --ignore-scripts && npm run build

FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
# Copy package.json for bin mapping
COPY package.json ./package.json
RUN npm install --omit=dev && chmod +x dist/index.js

ENTRYPOINT ["node", "dist/index.js"]
